name: 'Assign Issue on Keyword'

on:
  issue_comment:
    types: [created]

permissions:
  issues: write  # Ensures the workflow can write to issues
  pull-requests: write  # Ensures the workflow can write to pull requests

jobs:
  assign_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check for keyword
      id: keyword_check
      if: contains(github.event.comment.body, 'ASSIGN_ME')
      run: echo "Keyword found, proceeding to assign..."

    - name: Check for existing assignees
      id: check_assignees
      uses: actions/github-script@v4
      with:
        script: |
          const issue = await github.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          return issue.data.assignees.length > 0 ? { hasAssignees: false } : { hasAssignees: true };
          
    - name: Comment on the issue
      if: steps.keyword_check.conclusion == 'success' && steps.check_assignees.outputs.hasAssignees == 'true'
      uses: actions/github-script@v4
      with:
        script: |
          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Thanks for taking on this issue',
          });

    - name: Assign issue
      if: steps.keyword_check.conclusion == 'success' && steps.check_assignees.outputs.hasAssignees == 'true'
      uses: actions/github-script@v4
      with:
        script: |
          await github.issues.addAssignees({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: [context.actor]
          });
